name: Build, Test, and Deploy for Dev Branch

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Pull from GitHub
        run: |
          git stash
          git pull origin dev

      - name: Build Docker image
        run: docker build -t aihomework-dev:latest .

      - name: Save Docker image to tarball
        run: docker save aihomework-dev:latest -o aihomework-dev.tar

      - name: Upload Docker image to server
        env:
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
        run: |
          scp -i $SERVER_SSH_KEY aihomework-dev.tar $SERVER_USER@$SERVER_HOST:/var/www/aihomework/dev/

      - name: Load Docker image on server and start
        env:
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
        run: |
          ssh -i $SERVER_SSH_KEY $SERVER_USER@$SERVER_HOST << 'EOF'
          cd /var/www/aihomework/dev
          docker load -i aihomework-dev.tar
          docker-compose down
          docker-compose up -d
          EOF
