name: Build, Test, and Deploy for Prod Branch

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Pull from GitHub
        run: |
          git stash
          git pull origin main

      - name: Build Docker image
        run: docker build -t aihomework-prod:latest .

      - name: Save Docker image to tarball
        run: docker save aihomework-prod:latest -o aihomework-prod.tar

      - name: Upload Docker image to server
        env:
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
        run: |
          scp -i $SERVER_SSH_KEY aihomework-prod.tar $SERVER_USER@$SERVER_HOST:/var/www/aihomework/prod/

      - name: Load Docker image on server and start
        env:
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
        run: |
          ssh -i $SERVER_SSH_KEY $SERVER_USER@$SERVER_HOST << 'EOF'
          cd /var/www/aihomework/prod
          docker load -i aihomework-prod.tar
          docker-compose down
          docker-compose up -d
          EOF
